# Generated by Django 5.0.6 on 2024-06-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='sale_date',
            new_name='saleDate',
        ),
    ]
